### ISSUE TITLE
Add check for EOF error for fastq.gz

### ISSUE THREAD

**Issue by adswafford** [qiita-spots/qiita#3047]
When a fastq.gz is being generated by an upstream qc process, e.g. fastp, minimap2, etc. that is part of a terminated job, the output files are not overly problematic but after upload to Qiita, they throw an error only when they are processed leading to tedious removal and re-association of the prep file. 

Can we add a check to ensure that the fastq files will not cause an issue, perhaps at the time of association?

This script (or something like it) should do the job:

for file in *.fastq.gz;
do      lastchar_hex=`zcat $file | tail -c 1 | xxd -p`;
 if [[ $lastchar_hex != '0a' ]];
then  
 echo "File $file does not end with newline" >> EOF_error.log;  #likely reading out as banner error message.
   fi; 
done;

Recent example error in Qiita Admin:

2020-11-14 15:15:48.361423 | 2 | Error executing Shogun v1.0.8:['Traceback (most recent call last):\n', ' File "/home/qiita/miniconda3/envs/qp-shogun-072020/lib/python3.7/site-packages/qiita_client/plugin.py", line 266, in __call__\n qclient, job_id, job_info[\'parameters\'], output_dir)\n', ' File "/home/qiita/miniconda3/envs/qp-shogun-072020/lib/python3.7/site-packages/qiita_client/plugin.py", line 105, in __call__\n return self.function(qclient, server_url, job_id, output_dir)\n', ' File "/home/qiita/qiita_spots/qp-shogun/qp_shogun/shogun/shogun.py", line 198, in shogun\n comb_fp = generate_fna_file(out_dir, samples)\n', ' File "/home/qiita/qiita_spots/qp-shogun/qp_shogun/shogun/shogun.py", line 39, in generate_fna_file\n for header, seq, qual in readfq(fp):\n', ' File "/home/qiita/qiita_spots/qp-shogun/qp_shogun/shogun/utils.py", line 76, in readfq\n for line in fp: # read the sequence\n', ' File "/home/qiita/miniconda3/envs/qp-shogun-072020/lib/python3.7/gzip.py", line 300, in read1\n return self._buffer.read1(size)\n', ' File "/home/qiita/miniconda3/envs/qp-shogun-072020/lib/python3.7/_compression.py", line 68, in readinto\n data = self.read(len(byte_view))\n', ' File "/home/qiita/miniconda3/envs/qp-shogun-072020/lib/python3.7/gzip.py", line 493, in read\n raise EOFError("Compressed file ended before the "\n', 'EOFError: Compressed file ended before the end-of-stream marker was reached\n']
-- | -- | --

**Comment by antgonza** [comment]
I have been thinking about this problem for a while and AFAIK the issue with the proposed solution (and others I have looked into) is that we will basically need to uncompress every file to test it; which will make the creation/validation time dramatically for all studies. Also, just throwing this out there for consideration, I agree this is a real issue and a pain but IMOO it happens once in a while (considering how many studies we create and fastq.gz files are added to those studies) so not sure if we should make everything much slower.

Now, after another pass online it seems like we could use `gzip -t` to test the file, @adswafford could you verify that with the problematic file and perhaps compare it to your proposed solution? Another option is that you send me the location of the file and I test it ... 😄

**Comment by adswafford** [comment]
Agree that the decompression of all the files each time would be
suboptimal..

@Greg Poore <gdpoore@eng.ucsd.edu> do you have a corrupt file still that
you can test with the two commands below?

--
Austin D. Swafford, PhD
Director of Research- Innovations, Center for Microbiome Innovation
Jacobs School of Engineering | University of California- San Diego
O: 858-246-2906

*Follow @CMIDigest*

Subscribe to our mailing list
<https://signup.e2ma.net/signup/1853757/1802131/>

<http://ow.ly/kiac30dUAnc>    <http://ow.ly/fXyB30dUAoS>
<http://ow.ly/dKO130dUAuB>


PLEASE TAKE NOTICE: The information transmitted is intended only for the
person or entity to which it is addressed and may contain information that
is confidential, privileged and/or otherwise exempt from disclosure under
applicable state and federal law, including, but not limited to, privacy
standards imposed pursuant to the Federal Health Insurance Portability and
Accountability Act of 1996 (“HIPAA”). Any review, retransmission,
dissemination or other use of, or taking of any action in reliance upon
this information by persons or entities other than the intended recipient
is prohibited. If you receive this transmission in error, please contact
the sender immediately and delete the material from any computer. Thank
you.

**Comment by antgonza** [comment]
This checks actually are done by the plugin, not qiita. So moved this issue here: https://github.com/qiita-spots/qtp-sequencing/issues/36
