### ISSUE TITLE
download docs: clarifying file format downloaded

### ISSUE THREAD

**Issue by nick-youngblut** [qiita-spots/qiita#3170]
The [download docs](https://qiita.ucsd.edu/static/doc/html/downloading.html) state that a public artifact can be downloaded simply via `wget`. For example:

```
wget -O 6821.qza https://qiita.ucsd.edu/public_artifact_download/?artifact_id=6821
```

However, when I then tried to export the contents of the downloaded file:

```
qiime tools export --input-path 6821.qza --output-path tmp
```

...I get the error:

```
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/miniconda3/envs/qiime2-2021.11/bin/qiime", line 11, in <module>
    sys.exit(qiime())
  File "/ebio/abt3_projects/software/miniconda3/envs/qiime2-2021.11/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/ebio/abt3_projects/software/miniconda3/envs/qiime2-2021.11/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/ebio/abt3_projects/software/miniconda3/envs/qiime2-2021.11/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/ebio/abt3_projects/software/miniconda3/envs/qiime2-2021.11/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/ebio/abt3_projects/software/miniconda3/envs/qiime2-2021.11/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/ebio/abt3_projects/software/miniconda3/envs/qiime2-2021.11/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/ebio/abt3_projects/software/miniconda3/envs/qiime2-2021.11/lib/python3.8/site-packages/q2cli/builtin/tools.py", line 49, in export_data
    result = qiime2.sdk.Result.load(input_path)
  File "/ebio/abt3_projects/software/miniconda3/envs/qiime2-2021.11/lib/python3.8/site-packages/qiime2/sdk/result.py", line 66, in load
    archiver = archive.Archiver.load(filepath)
  File "/ebio/abt3_projects/software/miniconda3/envs/qiime2-2021.11/lib/python3.8/site-packages/qiime2/core/archive/archiver.py", line 299, in load
    archive = cls.get_archive(filepath)
  File "/ebio/abt3_projects/software/miniconda3/envs/qiime2-2021.11/lib/python3.8/site-packages/qiime2/core/archive/archiver.py", line 262, in get_archive
    archive = _ZipArchive(filepath)
  File "/ebio/abt3_projects/software/miniconda3/envs/qiime2-2021.11/lib/python3.8/site-packages/qiime2/core/archive/archiver.py", line 106, in __init__
    self.uuid = self._get_uuid()
  File "/ebio/abt3_projects/software/miniconda3/envs/qiime2-2021.11/lib/python3.8/site-packages/qiime2/core/archive/archiver.py", line 122, in _get_uuid
    raise ValueError("Archive has multiple root directories: %r"
ValueError: Archive has multiple root directories: {'mapping_files', 'Demultiplexed'}
```

After looking at the binary, I saw that it started with "PK", and was thus a zip file. It would help to clarify in the docs what is actually download via `https://qiita.ucsd.edu/public_artifact_download/?artifact_id=`. If multiple file types may be downloaded via that url pattern, then the docs could list all possible file types.

**Comment by antgonza** [comment]
Hi @nick-youngblut,

Thank you for opening this issue - we have added [this section to the documentation](https://github.com/qiita-spots/qiita/pull/3181/files#diff-99ff93afd233d323f0772428ed1d53b5aa38359e70419dfc171f7ac1a071cd8eR22); does it look OK to you or do you have any suggestions?

Best,

**Comment by nick-youngblut** [comment]
I think that will help out a lot! Thanks for updating the docs.

**Comment by antgonza** [comment]
Thank you for confirming. Note that this will become available during our next deployment, scheduled for March 28th.
