### ISSUE TITLE
IndexError: list index out of range for /analysis/dflt/sumary/

### ISSUE THREAD

**Issue by sjanssen2** [qiita-spots/qiita#3365]
I've set up a new Qiita instance in productive mode. The log files repeatedly list the following error. I assume this is due to the fact, that not a single analysis is present yet:

```
[E 240219 10:15:35 web:1669] Uncaught exception GET /analysis/dflt/sumary/ (127.0.0.1)
    HTTPServerRequest(protocol='https', host='localhost', method='GET', uri='/analysis/dflt/sumary/', version='HTTP/1.0', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/qiita/miniforge3/envs/qiita/lib/python3.9/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/qiita/miniforge3/envs/qiita/lib/python3.9/site-packages/tornado/web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "/home/qiita/miniforge3/envs/qiita/lib/python3.9/site-packages/qiita_core/util.py", line 83, in wrapper
        return func(*args, **kwargs)
      File "/home/qiita/miniforge3/envs/qiita/lib/python3.9/site-packages/qiita_pet/handlers/analysis_handlers/listing_handlers.py", line 98, in get
        info = self.current_user.default_analysis.summary_data()
      File "/home/qiita/miniforge3/envs/qiita/lib/python3.9/site-packages/qiita_db/user.py", line 500, in default_analysis
        qdb.sql_connection.TRN.execute_fetchlast())
      File "/home/qiita/miniforge3/envs/qiita/lib/python3.9/site-packages/qiita_db/sql_connection.py", line 49, in wrapper
        return func(self, *args, **kwargs)
      File "/home/qiita/miniforge3/envs/qiita/lib/python3.9/site-packages/qiita_db/sql_connection.py", line 336, in execute_fetchlast
        return self.execute()[-1][0][0]
    IndexError: list index out of range
[E 240219 10:15:35 web:2161] 500 GET /analysis/dflt/sumary/ (127.0.0.1) 51.84ms
```

**Comment by antgonza** [comment]
I think that one is because the user doesn't have a default analysis, which should be created during the user creation step. Which user are you using and how did you create it?

**Comment by sjanssen2** [comment]
I have used "sign up" through the Qiita website and manually "verified" the user via setting the user_level to 4

**Comment by antgonza** [comment]
That makes sense, bring back to unverified and use this code (this is what's run when you use the GUI):
```
from qiita_db.user import User
email = 'whatever@foo.bar'
User.verify_code(email, User(email).info['user_verify_code'], "create")
```

**Comment by sjanssen2** [comment]
works perfectly. Thanks!
